name: medicine_reminder
description: A medicine reminder app with Flutter, Riverpod, and Hive.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management (Updated to latest resolvable)
  flutter_riverpod: ^2.6.1

  # Local Storage (Hive)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.3.3

  # Alarms and Notifications
  # We are using ONLY local_notifications to avoid the background_executor errors
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  permission_handler: ^11.4.0

  # Utilities
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: "^0.14.4"

  # Code Generation for Hive Models
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png" # Path to your new PNG
  adaptive_icon_background: "#e8e8e8" # Matching your app's theme
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
